"""Platform-only pins in the hash-pinned locks: requirements a Linux-compiled lock drops but another platform installs.

pip-compile resolves for the container it runs in (linux/amd64), so a requirement whose marker is false there, such as
ipykernel's macOS-only appnope, never reaches the lock, and pip's hash mode then refuses to install the lock on macOS.
tools/compile_requirements.py appends each marked pin from the source with every file hash PyPI lists for it.

Failure modes (written before the code):

1. A marked pin in the source is missing from the compiled lock: it is appended with its marker and hashes.
2. pip-compile already locked the marked pin (the marker was true in the container): the lock is left unchanged.
3. A marked pin without an exact version: stop; a lock pin needs one version.
4. PyPI has no files for the version, the version is yanked or the request fails: stop and leave the lock unchanged.
5. A rerun appends the pin a second time: the result is the same as one run.
6. The appended pin breaks the lock check (a pin followed by hashes) or pip's format: the block matches pip-compile's;
   the requirement-locks hook on the real lock proves it.
"""

from __future__ import annotations

from pathlib import Path

import httpx
import pytest
import respx

from testkit import expect
from tools import compile_requirements

HASH_A = "a" * 64
HASH_B = "b" * 64
LOCK = """#
# This file is autogenerated by pip-compile with Python 3.12
#
ipykernel==7.4.0 \\
    --hash=sha256:{c}
    # via -r requirements_dev.in
zzz-last==1.0 \\
    --hash=sha256:{c}
    # via -r requirements_dev.in
""".format(c="c" * 64)
SOURCE = 'ipykernel==7.4.0\nappnope==1.0.0 ; sys_platform == "darwin"  # tool: macOS-only\n'


def pypi(version: str = "1.0.0", files: list[dict] | None = None, yanked: bool = False) -> httpx.Response:
    files = files if files is not None else [{"digests": {"sha256": HASH_B}}, {"digests": {"sha256": HASH_A}}]
    return httpx.Response(200, json={"info": {"version": version, "yanked": yanked}, "urls": files})


def write(tmp_path: Path, lock: str = LOCK, source: str = SOURCE) -> tuple[Path, Path]:
    (tmp_path / "requirements_dev.in").write_text(source, encoding="utf-8")
    (tmp_path / "requirements_dev.txt").write_text(lock, encoding="utf-8")
    return tmp_path / "requirements_dev.in", tmp_path / "requirements_dev.txt"


@respx.mock
def test_a_missing_marked_pin_is_appended_with_its_marker_and_every_hash(tmp_path: Path) -> None:
    respx.get("https://pypi.org/pypi/appnope/1.0.0/json").mock(return_value=pypi())
    source, lock = write(tmp_path)

    compile_requirements.add_platform_pins(source, lock)

    text = lock.read_text(encoding="utf-8")
    block = f'appnope==1.0.0 ; sys_platform == "darwin" \\\n    --hash=sha256:{HASH_A} \\\n    --hash=sha256:{HASH_B}\n    # via -r requirements_dev.in\n'
    expect.is_in(block, text)
    # Sorted among the other pins, as pip-compile writes them.
    expect.equal(text.index("appnope==") < text.index("ipykernel=="), True)


def test_a_pin_the_container_already_locked_is_left_alone(tmp_path: Path) -> None:
    locked = LOCK + f'appnope==1.0.0 ; sys_platform == "darwin" \\\n    --hash=sha256:{HASH_A}\n    # via ipykernel\n'
    source, lock = write(tmp_path, lock=locked)

    compile_requirements.add_platform_pins(source, lock)

    expect.equal(lock.read_text(encoding="utf-8"), locked)


def test_a_marked_requirement_without_one_version_stops(tmp_path: Path) -> None:
    source, lock = write(tmp_path, source='appnope>=1 ; sys_platform == "darwin"\n')

    with pytest.raises(compile_requirements.LockError, match="appnope"):
        compile_requirements.add_platform_pins(source, lock)

    expect.equal(lock.read_text(encoding="utf-8"), LOCK)


@respx.mock
@pytest.mark.parametrize(
    "response", [pypi(files=[]), pypi(yanked=True), httpx.Response(404), httpx.ConnectTimeout("timed out")], ids=["no files", "yanked", "not found", "timeout"]
)
def test_pypi_without_usable_files_stops_and_leaves_the_lock(tmp_path: Path, response: httpx.Response | Exception) -> None:
    route = respx.get("https://pypi.org/pypi/appnope/1.0.0/json")
    if isinstance(response, Exception):
        route.mock(side_effect=response)
    else:
        route.mock(return_value=response)
    source, lock = write(tmp_path)

    with pytest.raises(compile_requirements.LockError, match="appnope==1.0.0"):
        compile_requirements.add_platform_pins(source, lock)

    expect.equal(lock.read_text(encoding="utf-8"), LOCK)


@respx.mock
def test_a_rerun_gives_the_same_lock(tmp_path: Path) -> None:
    respx.get("https://pypi.org/pypi/appnope/1.0.0/json").mock(return_value=pypi())
    source, lock = write(tmp_path)

    compile_requirements.add_platform_pins(source, lock)
    once = lock.read_text(encoding="utf-8")
    compile_requirements.add_platform_pins(source, lock)

    expect.equal(lock.read_text(encoding="utf-8"), once)
