name: healthcare_realtime
version: "1.0.0"
config-version: 2

profile: healthcare_realtime

model-paths:
  - models

test-paths:
  - tests

macro-paths:
  - macros

clean-targets:
  - target
  - dbt_packages

models:
  healthcare_realtime:
    staging:
      +materialized: view

    marts:
      core:
        +materialized: table
        +table_type: iceberg
        +format: parquet

      analytics:
        +materialized: table
        +table_type: iceberg
        +format: parquet

seeds:
  healthcare_realtime:
    provider_history:
      +column_types:
        provider_npi: varchar
        provider_name: varchar
        taxonomy_code: varchar
        taxonomy_description: varchar
        provider_state: varchar
        valid_from: varchar
        valid_to: varchar
        is_current: boolean
        data_source: varchar
