healthcare_realtime:
  target: prod

  outputs:
    prod:
      type: athena
      database: awsdatacatalog
      schema: healthcare_realtime_dbt
      region_name: us-east-1
      s3_staging_dir: s3://imungai-healthcare-realtime/athena_results/dbt/
      s3_data_dir: s3://imungai-healthcare-realtime/dbt/
      s3_data_naming: schema_table_unique
      threads: 4
