#!/usr/bin/env bash
# Start, check, stop or reset the local Docker stack (deploy/local/compose.yaml).
#   start   generate deploy/local/.env once, render the Grafana dashboards, start Postgres, HAPI FHIR and Grafana,
#           wait until each is healthy
#   status  show the services and their localhost ports
#   stop    stop and remove the containers; the data volumes stay
#   reset   also delete the data volumes (needs CONFIRM_LOCAL_STACK_RESET=delete-local-stack-data)
# Run python -m e2e.local_stack after start to check the stack end to end.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
STACK_DIR="$REPO_ROOT/deploy/local"
STACK_ENV="$STACK_DIR/.env"
COMPOSE=(docker compose -f "$STACK_DIR/compose.yaml")
# HAPI FHIR takes about 1 to 3 minutes to create its schema on a new database.
READY_TIMEOUT_SECONDS="${LOCAL_STACK_READY_TIMEOUT_SECONDS:-300}"
RESET_CONFIRMATION="delete-local-stack-data"

usage() {
  echo "Usage: $0 start|status|stop|reset" >&2
  exit 2
}

# Write random passwords once. An existing file is never changed, because the data volumes keep the first passwords.
ensure_stack_env() {
  if [[ -f "$STACK_ENV" ]]; then
    return
  fi
  local name
  (
    umask 077
    {
      echo "# Generated by scripts/local/local_stack.sh; local only and ignored by Git."
      for name in LOCAL_POSTGRES_PASSWORD LOCAL_HAPI_DB_PASSWORD LOCAL_WAREHOUSE_DB_PASSWORD \
        LOCAL_GRAFANA_DB_PASSWORD LOCAL_GRAFANA_READER_PASSWORD LOCAL_GRAFANA_ADMIN_PASSWORD; do
        echo "$name=$(openssl rand -hex 24)"
      done
    } > "$STACK_ENV"
  )
  echo "Generated local passwords in deploy/local/.env."
}

wait_for() {
  local label="$1" url="$2" deadline=$((SECONDS + READY_TIMEOUT_SECONDS))
  until curl --silent --fail --output /dev/null "$url"; do
    if ((SECONDS >= deadline)); then
      echo "$label was not ready within $READY_TIMEOUT_SECONDS seconds; see: ${COMPOSE[*]} logs" >&2
      exit 1
    fi
    sleep 5
  done
  echo "$label is ready."
}

COMMAND="${1:-}"
case "$COMMAND" in
  start)
    docker info >/dev/null 2>&1 || { echo "Docker is not running; start Docker Desktop first." >&2; exit 1; }
    ensure_stack_env
    # Grafana loads the dashboards rendered for the local warehouse from deploy/grafana/dashboards/.
    (cd "$REPO_ROOT" && .venv/bin/python -m scripts.grafana.render_dashboards --target local --output "$STACK_DIR/grafana/dashboards")
    "${COMPOSE[@]}" up --detach --wait postgres
    "${COMPOSE[@]}" up --detach hapi grafana
    set -a
    source "$STACK_ENV"
    set +a
    wait_for "HAPI FHIR" "http://127.0.0.1:${LOCAL_HAPI_PORT:-8080}/fhir/metadata"
    wait_for "Grafana" "http://127.0.0.1:${LOCAL_GRAFANA_PORT:-3000}/api/health"
    echo "HAPI FHIR: http://127.0.0.1:${LOCAL_HAPI_PORT:-8080}/fhir"
    echo "Grafana:   http://127.0.0.1:${LOCAL_GRAFANA_PORT:-3000} (user admin; password LOCAL_GRAFANA_ADMIN_PASSWORD in deploy/local/.env)"
    ;;
  status)
    "${COMPOSE[@]}" ps
    ;;
  stop)
    "${COMPOSE[@]}" down
    ;;
  reset)
    if [[ "${CONFIRM_LOCAL_STACK_RESET:-}" != "$RESET_CONFIRMATION" ]]; then
      echo "Refusing to delete the local data volumes. Set CONFIRM_LOCAL_STACK_RESET=$RESET_CONFIRMATION." >&2
      exit 2
    fi
    "${COMPOSE[@]}" down --volumes
    ;;
  *)
    usage
    ;;
esac
