services:
  hapi-fhir:
    image: hapiproject/hapi:latest
    container_name: healthcare_realtime_hapi
    ports:
      - "8090:8080"
    environment:
      spring.datasource.url: jdbc:h2:file:/data/hapi
      spring.datasource.username: sa
      spring.datasource.password: ""
      spring.datasource.driverClassName: org.h2.Driver
      spring.jpa.properties.hibernate.dialect: ca.uhn.fhir.jpa.model.dialect.HapiFhirH2Dialect
      hapi.fhir.subscription.resthook_enabled: "true"
      hapi.fhir.subscription.websocket_enabled: "false"
    volumes:
      - hapi-data:/data
    restart: unless-stopped

volumes:
  hapi-data:
