name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  python:
    name: Python Checks
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"
          cache: pip

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt

      - name: Ruff
        run: ruff check .

      - name: Tests
        run: pytest tests -v
      
      - name: Run BIDMC tests
        run: |
          python -m pytest \
          services/vitals_simulator/tests \
          -v  
      

  terraform:
    name: Terraform Checks
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: "1.11.0"

      - name: Terraform Format
        run: terraform fmt -check -recursive infra

      - name: Terraform Init
        working-directory: infra
        run: terraform init -backend=false

      - name: Terraform Validate
        working-directory: infra
        run: terraform validate

  synthea:
    name: Synthea FHIR Generation
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: "17"

      - name: Install Synthea
        run: ./scripts/synthea_loader/scripts/install.sh

      - name: Generate test patient
        run: POPULATION=1 ./scripts/synthea_loader/scripts/generate.sh

      - name: Validate generated FHIR
        run: pytest scripts/synthea_loader/tests -v